"""
The triage agent. Given an Alert, this:
  1. Builds a context prompt from the alert + its linked events.
  2. Runs a Claude tool-use loop (query_logs, enrich_ip, get_process_tree,
     check_asset_criticality) so the model can investigate before concluding.
  3. Requires the model to call `submit_triage` to finalize -- this gives us
     a structured result instead of parsing free text, and guarantees every
     triage has a summary/confidence/reasoning even if the model would
     otherwise just ramble.
  4. Writes the result back onto the Alert row.

Requires ANTHROPIC_API_KEY to be set in the environment.
"""

from __future__ import annotations

import os

import anthropic
from sqlalchemy.orm import Session

from .models import Alert, AlertStatus, Severity
from .tools import TRIAGE_TOOLS, dispatch_tool

DEFAULT_MODEL = os.environ.get("SOC_AGENT_MODEL", "claude-sonnet-5")
MAX_TOOL_ROUNDS = 8

SYSTEM_PROMPT = """\
You are a Tier-1 SOC analyst assistant. You are given a security alert \
generated by a detection rule, along with its supporting log events. Your \
job is to investigate and triage it -- NOT to take any action.

Guidelines:
- Use the available tools to gather context before concluding anything. \
Don't guess at facts you could look up (e.g. don't assume an IP is \
malicious without calling enrich_ip; don't assume a host is critical \
without calling check_asset_criticality).
- Be skeptical. Many alerts are false positives or low-value noise \
(e.g. a known admin script, an internal scanner, a single mistyped \
password). Say so plainly when that's what you find -- don't inflate \
severity to seem thorough.
- Weigh asset criticality: the same technical event matters more against \
a high-criticality asset than a disposable one.
- When you're done, call submit_triage exactly once with your conclusion. \
Do not take or propose executing any action yourself -- only recommend.
"""


def _format_alert_context(alert: Alert) -> str:
    events = [link.event for link in alert.event_links]
    events.sort(key=lambda e: e.timestamp)

    lines = [
        f"ALERT: {alert.title}",
        f"Rule: {alert.rule_name} (source: {alert.rule_source})",
        f"Default severity from rule: {alert.severity.value}",
        f"Description: {alert.description}",
        "",
        f"Supporting events ({len(events)} total):",
    ]
    for e in events[:30]:
        lines.append(
            f"  [{e.timestamp.isoformat()}] host={e.host} type={e.event_type} "
            f"src_ip={e.src_ip} user={e.user} msg={e.message}"
        )
    if len(events) > 30:
        lines.append(f"  ... and {len(events) - 30} more (use query_logs to page through if needed)")

    return "\n".join(lines)


def triage_alert(session: Session, alert: Alert, model: str = DEFAULT_MODEL) -> dict:
    client = anthropic.Anthropic()

    events = [link.event for link in alert.event_links]
    if not events:
        raise ValueError(f"Alert {alert.id} has no linked events -- nothing to investigate.")
    alert_window = (min(e.timestamp for e in events), max(e.timestamp for e in events))

    messages = [{"role": "user", "content": _format_alert_context(alert)}]

    final_result = None
    for _round in range(MAX_TOOL_ROUNDS):
        response = client.messages.create(
            model=model,
            max_tokens=2000,
            system=SYSTEM_PROMPT,
            tools=TRIAGE_TOOLS,
            messages=messages,
        )

        messages.append({"role": "assistant", "content": response.content})

        tool_use_blocks = [b for b in response.content if b.type == "tool_use"]
        if not tool_use_blocks:
            # Model didn't call a tool at all -- nudge it toward submit_triage
            messages.append({
                "role": "user",
                "content": "Please call submit_triage to finalize your assessment.",
            })
            continue

        tool_results = []
        submitted = False
        for block in tool_use_blocks:
            if block.name == "submit_triage":
                final_result = dict(block.input)
                submitted = True
                # Tool-use turns require a result for every tool_use block,
                # even the terminal one, or the API will reject the next call.
                tool_results.append({
                    "type": "tool_result",
                    "tool_use_id": block.id,
                    "content": "Triage recorded.",
                })
                continue

            result = dispatch_tool(session, block.name, block.input, alert_window)
            tool_results.append({
                "type": "tool_result",
                "tool_use_id": block.id,
                "content": str(result),
            })

        messages.append({"role": "user", "content": tool_results})

        if submitted:
            break

    if final_result is None:
        raise RuntimeError(
            f"Agent did not submit a triage result for alert {alert.id} within {MAX_TOOL_ROUNDS} tool rounds."
        )

    alert.agent_summary = final_result["summary"]
    alert.agent_confidence = final_result["confidence"]
    alert.agent_reasoning = final_result["reasoning"]
    alert.agent_recommended_actions = final_result.get("recommended_actions", [])
    alert.severity = Severity(final_result["severity_assessment"])
    alert.status = AlertStatus.FALSE_POSITIVE if final_result.get("is_false_positive") else AlertStatus.TRIAGED

    return final_result
